url: http://pytorch.org
name: PyTorch
description: 'Scientific Computing...'
latest_version: 1.0
baseurl:
relative_permalinks: false
timezone: America/Los_Angeles
sass:
    sass_dir: _sass # default
    style: compressed
safe: true
highlighter: rouge
markdown: kramdown
future: true
include:
    - _static
    - _modules
    - _sources
    - _tensor_str.html
    - _utils.html
exclude:
    - node_modules
    - README.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
    
# google_site_verification: eOAFtDphTbbm4OPKva2d3Z0Z_2bBxWMGdkD0IRQ6VeA

plugins:
  - jekyll-feed
